[project]
name = "apprating"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=1.7.4.2",
    "notebook>=7.4.0",
    "pandas>=2.2.3",
]
